name: Kubernetes CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Frontend Build and Test
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Frontend Dependencies
      working-directory: ./frontend
      run: npm ci

    - name: Run Frontend Tests
      working-directory: ./frontend
      run: npm test

    # Docker Build and Push
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Frontend Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        push: true
        tags: omerbenda98/puppy-adoption-frontend:${{ github.sha }}

    # Update Kubernetes manifests
    - name: Update Kubernetes deployment
      run: |
        cd k8s/production
        # Update the image tag in deployment yaml
        sed -i 's|image: .*|image: omerbenda98/puppy-adoption-frontend:${{ github.sha }}|' frontend.yaml
        
    # Optional: If you want to auto-commit the updated manifests
    - name: Commit updated manifests
      run: |
        git config --global user.name 'GitHub Actions Bot'
        git config --global user.email 'actions@github.com'
        git add k8s/production/frontend.yaml
        git commit -m "Update deployment image to ${{ github.sha }}"
        git push
