name: Kubernetes CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Frontend Build and Test
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Frontend Dependencies
        working-directory: .
        run: npm ci

      - name: Run Frontend Tests
        working-directory: .
        run: npm test

      # Docker Build and Push
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Frontend Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: omerbenda98/puppy-adoption-frontend:${{ github.sha }}

      # Checkout and update K8s repo
      - name: Checkout K8s repository
        uses: actions/checkout@v4
        with:
          repository: omerbenda98/puppy-adoption-k8s
          token: ${{ secrets.K8S_REPO_TOKEN }}
          path: k8s-repo

      - name: Update Kubernetes deployment
        run: |
          cd k8s-repo
          sed -i 's|image: omerbenda98/puppy-adoption-frontend:.*|image: omerbenda98/puppy-adoption-frontend:${{ github.sha }}|' development/frontend/deployment.yaml
          sed -i 's|image: omerbenda98/puppy-adoption-frontend:.*|image: omerbenda98/puppy-adoption-frontend:${{ github.sha }}|' production/frontend/deployment.yaml

      - name: Commit updated manifests
        run: |
          cd k8s-repo
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add main.yaml
          git commit -m "Update frontend deployment image to ${{ github.sha }}"
          git push
