name: CI Pipeline
on:
  push:
    branches:
      - staging
      - main
  pull_request:
    branches: [main]


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install Frontend Dependencies
        run: npm ci
      - name: Run Frontend Tests
        run: npm test

  trigger-jenkins-staging:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/staging'
    steps:
      - name: Trigger Jenkins Staging Pipeline
        run: |
          curl -X POST \
          -u ${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }} \
          'http://44.207.146.138:8090/job/frontend-staging-pipeline/build?token=frontend-pipeline-token'

  trigger-jenkins-production:
    needs: test
    runs-on: ubuntu-latest
    # Only trigger production deployment after PR is merged to main
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Trigger Jenkins Production Pipeline
        run: |
          curl -X POST \
          -u ${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }} \
          'http://44.207.146.138:8090/job/frontend-production-pipeline/build?token=prod-trigger-token'
