name: CI Pipeline

on:
  push:
    branches: [main, staging]
  pull_request:
    branches: [main, staging]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Frontend Dependencies
        run: npm ci

      - name: Run Frontend Tests
        run: npm test

  trigger-jenkins:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref_name == 'staging'
    steps:
      - name: Trigger Jenkins Job
        run: |
          CRUMB=$(curl -s -u ${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }} \
          'http://44.207.146.138:8090/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,":",//crumb)')

          curl -X POST -H "$CRUMB" \
          -u ${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }} \
          'http://44.207.146.138:8090/job/frontend-pipeline/buildWithParameters?BRANCH_NAME=staging'
